### ISSUE TITLE
After installation, homepage takes > 10 sec to load

### ISSUE THREAD

**Issue by connecteev** [rverrips/todomvc-livewire#1]
After installation, homepage takes > 10 sec to load

**Comment by rverrips** [comment]
Could you please provide some more details, @connecteev, such as:
- Was it just slow on the initial startup, or every time  
- Which version of php are you using
- If you install the standard lavarel application (without todomvc-livewire) and run that does it take the same time to load

**Comment by connecteev** [comment]
@rverrips to answer your questions:
* this happens every time.
* I'm on PHP version 7.2
* It only happens with this repository

**Comment by yotmv** [comment]
Had the same issue, resolved it by downloading local copies of css files: base & index 
Think the CDN might be having some issues

<link rel="stylesheet" href="https://unpkg.com/todomvc-common@1.0.5/base.css">
<link rel="stylesheet" href="https://unpkg.com/todomvc-app-css@2.2.0/index.css">

**Comment by rverrips** [comment]
Thanks @yotmv - Did that fix your issue, @connecteev?

**Comment by connecteev** [comment]
@yotmv @rverrips this works now without any changes. Looks like the CDN issues went away.
